# Generated by Django 4.1.7 on 2023-03-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_billinginfo_bordercrossing_port_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
    ]
