# Generated by Django 4.1.7 on 2023-03-05 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_billinginfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='port',
            name='created',
        ),
        migrations.RemoveField(
            model_name='port',
            name='updated',
        ),
    ]
