# Generated by Django 4.1.7 on 2023-03-05 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_port_created_remove_port_updated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bordercrossing',
            name='created',
        ),
    ]
