# Generated by Django 4.1.7 on 2023-03-05 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_bordercrossing_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='country',
            field=models.CharField(max_length=50, verbose_name='Pays'),
        ),
    ]
