# Generated by Django 4.1.7 on 2023-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_billinginfo_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default={}),
        ),
    ]
