# Generated by Django 4.1.7 on 2023-03-07 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_office_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default={'operation__type': None, 'transport': None}),
        ),
    ]
