# Generated by Django 4.1.7 on 2023-03-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_office_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='access',
            field=models.JSONField(default={'transport': None}),
        ),
        migrations.AlterField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default={'transport': None}),
        ),
    ]
