# Generated by Django 4.1.7 on 2023-03-07 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_office_access'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='limitation',
            new_name='limit',
        ),
    ]
