# Generated by Django 4.1.7 on 2023-03-07 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rename_limitation_office_limit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='office',
            old_name='limit',
            new_name='limitation',
        ),
    ]
