# Generated by Django 4.1.7 on 2023-03-07 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_remove_office_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default={'business': '', 'created': '', 'created_by': '', 'end_point': '', 'entry_point': '', 'exit_point': '', 'exporter': '', 'forwarder': '', 'load_point': '', 'manifest_bp_no': '', 'operation_type': '', 'payment_method': '', 'status': '', 'transport': '', 'unload_point': '', 'updated': '', 'updated_by': ''}),
        ),
    ]
