# Generated by Django 4.1.7 on 2023-03-07 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_office_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default={'business': None, 'created': None, 'created_by': None, 'end_point': None, 'entry_point': None, 'exit_point': None, 'exporter': None, 'forwarder': None, 'load_point': None, 'manifest_bp_no': None, 'operation_type': None, 'payment_method': None, 'status': None, 'transport': None, 'unload_point': None, 'updated': None, 'updated_by': None}),
        ),
    ]
