# Generated by Django 4.1.7 on 2023-03-07 11:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_office_limitation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.office'),
        ),
    ]
