# Generated by Django 4.1.7 on 2023-03-13 21:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_alter_user_company_alter_user_office'),
    ]

    operations = [
        migrations.AlterField(
            model_name='office',
            name='limitation',
            field=models.JSONField(default=core.utils.default_limitation),
        ),
    ]
