# Generated by Django 4.1.7 on 2023-03-17 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_alter_office_limitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
