# Generated by Django 4.1.7 on 2023-03-17 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_alter_billinginfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='created',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated',
        ),
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
    ]
