# Generated by Django 4.1.7 on 2023-03-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_remove_unit_created_remove_unit_updated_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producttype',
            name='created',
        ),
        migrations.RemoveField(
            model_name='producttype',
            name='updated',
        ),
    ]
