# Generated by Django 4.1.7 on 2023-03-19 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_remove_producttype_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
