# Generated by Django 4.1.7 on 2023-03-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_alter_billinginfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='office',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Création'),
        ),
    ]
