# Generated by Django 4.1.7 on 2023-03-19 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_alter_billinginfo_name_alter_office_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billinginfo',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
    ]
