# Generated by Django 4.1.7 on 2023-03-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpoint',
            name='device_info',
        ),
        migrations.AlterField(
            model_name='operation',
            name='operation_type',
            field=models.CharField(choices=[('Exportation', 'Exportation')], max_length=12, verbose_name='Operation Type'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='payment_method',
            field=models.CharField(blank=True, choices=[(None, None), ('WALLET', 'Provision'), ('PROOF OF PAYMENT', 'Proof of Payment')], default=None, max_length=30, null=True),
        ),
    ]
