# Generated by Django 4.1.7 on 2023-03-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_remove_operation_comment_operation_business_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OperationManifest',
        ),
    ]
