# Generated by Django 4.1.7 on 2023-03-26 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_historicalproduct_historicaloperation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalcompany',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='entry_point',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='exit_point',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='load_point',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='unload_point',
        ),
        migrations.RemoveField(
            model_name='historicaloperation',
            name='updated_by',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='history_user',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='operation',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='product_type',
        ),
        migrations.RemoveField(
            model_name='historicalproduct',
            name='updated_by',
        ),
        migrations.DeleteModel(
            name='HistoricalCheckPoint',
        ),
        migrations.DeleteModel(
            name='HistoricalCompany',
        ),
        migrations.DeleteModel(
            name='HistoricalOperation',
        ),
        migrations.DeleteModel(
            name='HistoricalProduct',
        ),
    ]
