# Generated by Django 4.1.7 on 2023-03-05 23:59

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0005_remove_operation_arrival_remove_operation_departure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=django_countries.fields.CountryField(default='CD', max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
