# Generated by Django 4.1.7 on 2023-03-06 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0006_business_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='country',
        ),
    ]
