# Generated by Django 4.1.7 on 2023-03-06 00:04

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0007_remove_business_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='country',
            field=django_countries.fields.CountryField(default='CD', max_length=2, verbose_name='Country'),
            preserve_default=False,
        ),
    ]
