# Generated by Django 4.1.7 on 2023-03-07 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0008_business_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('PRE-VALIDATE', 'Pre-Validate'), ('VALIDATE', 'Validate'), ('IN_REVIEW', 'In review'), ('COMPLETED', 'Completed'), ('REJECTED', 'Rejected')], default='CREATED', max_length=12, verbose_name='Status'),
        ),
    ]
