# Generated by Django 4.1.7 on 2023-03-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0012_remove_product_is_transship_product_is_transshiped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_transshiped',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_transshipped',
            field=models.BooleanField(default=False, verbose_name='Is transshipped'),
        ),
        migrations.AlterField(
            model_name='product',
            name='penalty',
            field=models.IntegerField(default=0, help_text='The penalty is applied in %', verbose_name='Penalty applied'),
        ),
    ]
