# Generated by Django 4.1.7 on 2023-03-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0013_remove_product_is_transshiped_product_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_active',
        ),
        migrations.AddField(
            model_name='product',
            name='is_activated',
            field=models.BooleanField(default=True, verbose_name='Is activated'),
        ),
    ]
