# Generated by Django 4.1.7 on 2023-03-08 12:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0015_company_alter_operation_business_delete_business'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='users',
        ),
    ]
