# Generated by Django 4.1.7 on 2023-03-13 21:36

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0018_rename_business_operation_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='cost',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default=None, default_currency='USD', max_digits=14, null=True, verbose_name='Cost($)'),
        ),
        migrations.AlterField(
            model_name='operation',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUBMITTED', 'Submitted'), ('PRE-VALIDATE', 'Pre-Validate'), ('VALIDATE', 'Validate'), ('IN_REVIEW', 'In review'), ('COMPLETED', 'Completed'), ('PAID', 'Paid'), ('REJECTED', 'Rejected')], default='CREATED', max_length=12, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_activated',
            field=models.BooleanField(default=True, help_text='This ATM is active', verbose_name='Is activated'),
        ),
    ]
