# Generated by Django 4.1.7 on 2023-03-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0020_product_total_product_total_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='penalty',
            field=models.IntegerField(default=0, help_text='The penalty is applied in %', null=True, verbose_name='Penalty applied'),
        ),
    ]
