# Generated by Django 4.1.7 on 2023-03-17 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0021_alter_product_penalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_transshipped',
            field=models.BooleanField(default=False, null=True, verbose_name='Is transshipped'),
        ),
    ]
