# Generated by Django 4.1.7 on 2023-03-17 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0022_alter_product_is_transshipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_activated',
            field=models.BooleanField(default=True, help_text='This ATM is active', null=True, verbose_name='Is activated'),
        ),
    ]
