# Generated by Django 4.1.7 on 2023-03-27 14:31

import django.core.validators
from django.db import migrations, models
import wallet.models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='proof_of_payment',
            field=models.FileField(blank=True, default=None, help_text='Format supported : pdf,jpg,jpeg,png', null=True, upload_to=wallet.models.upload_directory_file, validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Proof of payment'),
        ),
    ]
